import { ArrowRight, ArrowUpRight, BrainCircuit, CloudCog, Code2, Layers3, LifeBuoy, ShieldCheck, Workflow } from 'lucide-react';
import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';
import { Container } from '@/components/ui/Container';
import { Button } from '@/components/ui/Button';

export default function HomePage() {
  return (
    <>
      <Navbar />
      <main>
        <section className="hero-band overflow-hidden">
          <Container className="relative grid min-h-[650px] items-center gap-14 py-16 lg:grid-cols-[0.92fr_1.08fr] lg:py-20">
            <div className="relative z-10">
              <div className="eyebrow mb-7"><span className="eyebrow-dot" /> Product engineering, end to end</div>
              <h1 className="max-w-[680px] text-5xl font-semibold leading-[1.02] tracking-normal text-[#f6f7f1] sm:text-6xl lg:text-[4.5rem]">
                Software that moves your business <span className="text-[#d8f078]">forward.</span>
              </h1>
              <p className="mt-7 max-w-xl text-lg leading-8 text-white/65">Nexiquill is your product engineering partner, turning ambitious ideas into dependable SaaS platforms, intelligent tools, and digital experiences.</p>
              <div className="mt-9 flex flex-col gap-3 sm:flex-row">
                <Button href="/contact" className="group gap-2 bg-[#d8f078] text-[#171b14] shadow-none hover:bg-[#e6fb9a]">Start a conversation <ArrowRight size={17} /></Button>
                <Button href="/services" variant="secondary" className="gap-2">Explore services <ArrowUpRight size={16} /></Button>
              </div>
              <div className="mt-12 flex items-center gap-3 text-sm text-white/55"><span className="h-2 w-2 rounded-full bg-[#d8f078]" /> One team from idea through iteration</div>
            </div>
            <div className="relative mx-auto w-full max-w-[600px] lg:ml-auto">
              <div className="absolute -right-16 -top-16 h-52 w-52 rounded-full bg-[#d8f078]/10 blur-3xl" />
              <div className="relative overflow-hidden rounded-lg border border-white/10 bg-[#f5f6f1] text-[#20251f] shadow-[0_32px_100px_-42px_rgba(0,0,0,0.8)]">
                <div className="flex items-center justify-between border-b border-[#20251f]/10 px-5 py-4"><div className="flex items-center gap-2.5"><span className="grid h-7 w-7 place-items-center rounded-md bg-[#20251f] text-[#d8f078]"><Layers3 size={14} /></span><span className="text-xs font-semibold tracking-wide">NEXIQUILL / PRODUCT PREVIEW</span></div><span className="text-[10px] text-[#667064]">ILLUSTRATIVE UI</span></div>
                <div className="grid min-h-[350px] sm:grid-cols-[130px_1fr]">
                  <aside className="hidden border-r border-[#20251f]/10 p-4 sm:block"><p className="mb-4 px-2 text-[9px] font-semibold tracking-[0.16em] text-[#92998d]">WORKSPACE</p>{['Overview', 'Projects', 'Analytics', 'Settings'].map((item, index) => <div key={item} className={`mb-1 flex items-center gap-2 rounded-md px-2 py-2 text-[10px] ${index === 0 ? 'bg-[#20251f] text-white' : 'text-[#727b70]'}`}><span className={`h-1.5 w-1.5 rounded-full ${index === 0 ? 'bg-[#d8f078]' : 'bg-[#bdc3b7]'}`} />{item}</div>)}</aside>
                  <div className="p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] text-[#828a7e]">MONDAY, 28 SEPTEMBER</p><h2 className="mt-1 text-xl font-semibold tracking-normal">Good morning, team</h2></div><span className="rounded-md border border-[#20251f]/10 bg-white px-2.5 py-1.5 text-[9px] text-[#5f685d]">Last 30 days</span></div>
                    <div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-md border border-[#20251f]/10 bg-white p-3.5"><p className="text-[9px] text-[#737c70]">PRODUCT FOCUS</p><p className="mt-2 text-2xl font-semibold">Roadmap</p><p className="mt-1 text-[9px] text-[#5f9067]">Scope in motion</p></div><div className="rounded-md border border-[#20251f]/10 bg-white p-3.5"><p className="text-[9px] text-[#737c70]">NEXT MILESTONE</p><p className="mt-2 text-xl font-semibold">Build review</p><p className="mt-1 text-[9px] text-[#5f9067]">Ready for feedback</p></div></div>
                    <div className="mt-3 rounded-md border border-[#20251f]/10 bg-white p-3.5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold">Delivery rhythm</p><p className="mt-1 text-[9px] text-[#8a9186]">A steady path from idea to launch</p></div><span className="text-[9px] text-[#5f9067]">IN PROGRESS</span></div><div className="mt-4 flex h-[90px] items-end gap-1.5 border-b border-[#20251f]/10 pb-1">{[38, 52, 44, 68, 56, 74, 63, 88, 70, 96, 78, 100].map((height, index) => <span key={index} className={`flex-1 rounded-t-[2px] ${index > 8 ? 'bg-[#d8f078]' : 'bg-[#cbd1c3]'}`} style={{ height: `${height}%` }} />)}</div><div className="mt-2 flex justify-between text-[8px] text-[#92998d]"><span>DISCOVER</span><span>DESIGN</span><span>BUILD</span><span>LAUNCH</span></div></div>
                    <div className="mt-3 flex items-center gap-2 rounded-md bg-[#e9eddd] px-3.5 py-2.5"><ShieldCheck size={14} className="text-[#536e3a]" /><span className="text-[9px] font-medium">Your data is encrypted and protected</span></div>
                  </div>
                </div>
                <div className="flex items-center justify-between border-t border-[#20251f]/10 px-5 py-3 text-[9px] text-[#858d81]"><span>Illustrative product interface</span><span>BUILT FOR WHAT&apos;S NEXT</span></div>
              </div>
            </div>
          </Container>
        </section>
        <section className="border-b border-[#20251f]/10 bg-[#e9ecdf] py-5"><Container className="flex flex-wrap items-center justify-between gap-x-8 gap-y-3 text-xs font-medium text-[#566051]"><span className="text-[10px] font-semibold tracking-[0.16em] text-[#80897b]">ONE PARTNER, END TO END</span><span>Product strategy</span><span>Experience design</span><span>Engineering</span><span>Cloud & AI</span><span>Ongoing support</span></Container></section>
        <section className="py-24 sm:py-28" id="services"><Container><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div className="max-w-2xl"><p className="section-kicker">WHAT WE DO</p><h2 className="section-title">Everything your product needs to go further.</h2></div><p className="max-w-md pb-1 text-base leading-7 text-[#697165]">From a first clickable idea to the systems behind your next stage of growth, we bring the right disciplines together.</p></div>
          <div className="mt-12 grid gap-px overflow-hidden rounded-lg border border-[#20251f]/10 bg-[#20251f]/10 sm:grid-cols-2 xl:grid-cols-3">{[
            [Layers3, 'SaaS product development', 'From first product brief to a secure, scalable platform your customers can rely on.'], [Code2, 'Web applications', 'Fast, considered web experiences built around the work your users need to get done.'], [BrainCircuit, 'AI & automation', 'Useful AI features and workflow automation, integrated with care and clear guardrails.'], [CloudCog, 'Cloud & DevOps', 'Cloud foundations, delivery pipelines, and observability designed for steady growth.'], [Workflow, 'Product modernization', 'Make legacy systems easier to change, more reliable, and ready for what comes next.'], [LifeBuoy, 'Ongoing engineering', 'A long-term product partner for improvements, support, and the next release.'],
          ].map(([Icon, title, text], index) => { const ServiceIcon = Icon as typeof Layers3; return <a href="/services" key={title as string} className="group min-h-[220px] bg-[#f6f7f1] p-6 transition-colors hover:bg-white sm:p-7"><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-md bg-[#e8eadf] text-[#30382b] transition-colors group-hover:bg-[#d8f078]"><ServiceIcon size={19} /></span><span className="text-xs text-[#9ba195]">0{index + 1}</span></div><h3 className="mt-6 text-lg font-semibold tracking-normal">{title as string}</h3><p className="mt-2 max-w-sm text-sm leading-6 text-[#70786d]">{text as string}</p><ArrowUpRight size={16} className="mt-4 text-[#818a7c] transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></a>; })}</div>
          <div className="mt-7"><Button href="/services" variant="secondary" className="gap-2">See how we can help <ArrowRight size={15} /></Button></div></Container></section>
        <section className="bg-[#e9ecdf] py-24 sm:py-28" id="approach"><Container className="grid gap-14 lg:grid-cols-[0.82fr_1.18fr] lg:items-start"><div className="lg:sticky lg:top-28"><p className="section-kicker">HOW WE WORK</p><h2 className="section-title">Small steps. Strong foundations. Real momentum.</h2><p className="mt-5 max-w-md leading-7 text-[#687064]">Senior attention, transparent decisions, and a delivery rhythm that keeps the important work moving.</p><div className="mt-8"><Button href="/about" variant="secondary" className="gap-2">Meet Nexiquill <ArrowUpRight size={15} /></Button></div></div><div className="divide-y divide-[#20251f]/15 border-y border-[#20251f]/15">{[['01', 'Discover', 'We align on users, business goals, constraints, and the right first release.'], ['02', 'Design & build', 'A focused team shapes the experience and ships in clear, reviewable increments.'], ['03', 'Launch & learn', 'We prepare for production, watch how it performs, and improve from real feedback.']].map(([number, title, text]) => <div key={number} className="grid gap-4 py-7 sm:grid-cols-[70px_1fr] sm:gap-6"><span className="text-sm font-medium text-[#859077]">{number} / 03</span><div><h3 className="text-xl font-semibold tracking-normal">{title}</h3><p className="mt-2 max-w-lg leading-7 text-[#687064]">{text}</p></div></div>)}</div></Container></section>
        <section className="py-24 sm:py-28"><Container><div className="relative overflow-hidden rounded-lg bg-[#20251f] px-7 py-12 text-[#f6f7f1] sm:px-12 sm:py-16 lg:px-16"><div className="absolute -right-10 -top-20 h-72 w-72 rounded-full border border-white/10" /><div className="absolute -right-1 top-[-52px] h-56 w-56 rounded-full border border-white/10" /><div className="relative flex flex-col gap-8 md:flex-row md:items-end md:justify-between"><div className="max-w-2xl"><p className="text-xs font-semibold tracking-[0.18em] text-[#d8f078]">HAVE A PRODUCT IN MIND?</p><h2 className="mt-4 text-3xl font-semibold leading-tight tracking-normal sm:text-4xl">Let&apos;s make your next idea real.</h2><p className="mt-4 max-w-xl leading-7 text-white/60">Tell us what you&apos;re building, where you&apos;re stuck, or where you want to go. We&apos;ll work out the next step together.</p></div><Button href="/contact" className="group shrink-0 gap-2 bg-[#d8f078] text-[#171b14] shadow-none hover:bg-[#e6fb9a]">Talk to our team <ArrowUpRight size={16} /></Button></div></div></Container></section>
      </main>
      <Footer />
    </>
  );
}
